### ISSUE TITLE
[Bug]: Missing images if the "Enable responsive images" has been disabled

### ISSUE THREAD

**Issue by Feriman22** [GetPublii/Publii#1094]
### Operating system

Windows 10

### Publii version

0.39.1 (build 15483)

### Bug description

Images are missing in sidebar if the "Enable responsive images" option has been disabled, even if I Regenerate thumbnails.

The image would be on "../Publii/sites/ferimancom/preview/media/posts/64/responsive/image-xs.png" path, but it doesn't exist here.

I use the Technews 2.4.0.0 theme.

The issue looks like this:

![missing-images](https://user-images.githubusercontent.com/22872515/159589256-2d7cb0f2-1d11-45ec-8521-be04944aaa2c.png)

### Steps to reproduce

1. Use "Technews" theme
2. Create a new article with featured image
3. Disable the "Enable responsive images" option
4. Preview your changes

**Comment by bobmitro** [comment]
Hey, 
It's not an app issue, the Technews theme displays a fixed thumbnail size (urlXs) in the Featured section:

`<img   src="{{urlXs}}"  class="lazyload" {{ lazyload "lazy" }}   alt="{{alt}}" height="{{height}}" width="{{height}}">`

So if the "Enable responsive images" option is disabled, the XS thumbnail size is not generated.  
And that's why you don't get a thumbnail in the Featured section.

If you want to display here an original image (which I do not recommend due to the big size of the photo) change the `{{urlXs}}` to `{{url}}`.

**Comment by Feriman22** [comment]
Hi,

Thanks for your quick response! You're right, it's a theme bug in that case. Can you fix it somehow, or will it be a manual step if someone does the same?

**Comment by bobmitro** [comment]
Fixed in the Technews v.2.5.2.0 - https://marketplace.getpublii.com/themes/technews/
