### ISSUE TITLE
Dependency error with OpenSuse

### ISSUE THREAD

**Issue by camckay** [GetPublii/Publii#1112]
RPM fails on OpenSuse (Leap and Tumbleweed) looking for libXtst. However, this is provided by libXtst6 and already installed on my system.

**Comment by dziudek** [comment]
Hi, if Publii works on your distribution - it's great news. 

At this moment due large amount of different linux distributions and configurations and their problems - we have no time to solve it case by case, especially if there is a way to make Publii working anyway. 

Because every case is a very niche and time consuming to reproduce. Of course if somebody in the community will be able to find and propose the solution - it will be great. But from our point of view - till Publii works on a specific configuration, then it is enough to skip the issue and focus on more important ones :)
