### ISSUE TITLE
[Documentation]: Netlify outdated

### ISSUE THREAD

**Issue by ShalokShalom** [GetPublii/Publii#1155]
### Operating system

Linux Garuda

### Publii version

current

### Bug description

Your homepage is showing an outdated version of Netlify. 

First, the upload field to drop the index folder seems to appear now just, when you click on Sites (I already have sites, so maybe thats why its the case for me)

And another thing is, that it seemingly does not require a zipped folder anymore, but a blank: 

![Screenshot_59](https://user-images.githubusercontent.com/6344099/197240859-0f89afca-1020-4817-ac00-24a38f4f786d.png)

I have the index.html.zip from your CDN in the Downloads folder

https://getpublii.com/docs/build-a-static-website-with-netlify.html

**Comment by ShalokShalom** [comment]
Another issue: 

![Screenshot_61](https://user-images.githubusercontent.com/6344099/197241391-4b3cfb3e-4971-46c2-aa3e-7f239ec3cf04.png)

I recommend to redo this whole entire Netlify tutorial. 

Since your webpage is - for whatever reason - not open source, can I not contribute 🤷🏼‍♂️

**Comment by ShalokShalom** [comment]
Yep: Also the next step has the API token on another place.

**Comment by bobmitro** [comment]
This issue is not related to the app and is closed now. Thank you for your help.

**Comment by ShalokShalom** [comment]
What?

**Comment by ShalokShalom** [comment]
This has to be one of the most shitty reaction, I got in almost 10 years of contributing to open source. 

Your documentation is out of sync, and you close the corresponding issue, simply because you failed to provide an appropriate way to report, or even fix these issues in the first place?

Are you serious?

**Comment by dziudek** [comment]
@ShalokShalom

First of all - I have locked this issue conversation, because your response is absolutely not-acceptable for us. Used words are very offensive and if you participate so long in open source communities  you should strongly rethink your approach to other people who spent their free time doing things which gives great free tools for others. 

Why @bobmitro closed this issue? We are closing all issues which are not related directly to the app, because a lot of issues was like this and it made harder to manage and track real app issues/feature propositions.

> Your documentation is out of sync, and you close the corresponding issue, simply because you failed to provide an appropriate way to report, or even fix these issues in the first place?

First of all - when you open a new issue there is clearly stated that Github issues are for Publii bugs/features and the community forum is for general queries - your report is not a bug or feature request - that's why it has been closed:

<img width="1147" alt="screen" src="https://user-images.githubusercontent.com/22004/197349058-593e9f0a-d598-452e-a8b9-2f35d07938ff.png">

@bobmitro maybe responded too short, but he wrote "Thanks for your help", because we have added Netlify tutorial for our list to be updated in short future in our internal ToDo. 

@ciznov2014 - thanks for the report - we will also re-check Gitlab tutorial. The deployment methods are changing in their configuration part quite often and it is normal that they can be outdated. We usually fix these issues in few weeks according to our current workload after discovering these changes.

> Had hopes for Publii but clearly going nowhere atm.

I am sorry that you think like this, we are constantly improving Publii - new release is around the corner. The deployment methods configuration is not a critical part of Publii. We are updating them if we spot diametrical changes during our tests, but saying that the app is going nowhere, because some small part of documentation is outdated is quite exaggerated in my opinion.
