### ISSUE TITLE
[Bug]: Publi crashes on export or preview at 80%

### ISSUE THREAD

**Issue by Khoramyar** [GetPublii/Publii#1162]
### Operating system

fedora 36

### Publii version

0.41.1 build 15919

### Post editor

WYSIWYG editor

### Bug description

When trying to render a preview or export, publii crashes at 80%.

It's a javascript crash as I looked at the other same issues here but as also submit form don't work on the publii website, I have to write here.

Publii on Fedora, latest version, with documentation theme, latest version ( v 1.8 )

Thank you.

**Comment by Khoramyar** [comment]
OK it turns out throwing the site away and making a new one is faster than getting support here.

I'll close the ticket.

**Comment by barigorokarl** [comment]
Okay, I got the same error and dug through the logs in `~/.config/Publii/logs`.

Turns out my particular problem was, that the generated name of a post html file was too long.
It did not help to shorten the slug (SEO / Post slug), **what did help was to shorten the title of the post**.

Hope that helps.
