### ISSUE TITLE
Markdown syntax

### ISSUE THREAD

**Issue by eapyl** [GetPublii/Publii#117]
Thank you for the great tool. 
Will it be possible to support markdown syntax additionally or allow to import markdown document into post editor? So it will be easy to write posts.
Thanks.

**Comment by dziudek** [comment]
Hi @eapyl,

Markdown support is in our future features list but at this moment without any ETA. The main issue is migration from existing sites to markdown-based websites and allowing some features available in the current WYSIWYG editor in the markdown editor (internal linking, images upload etc.). I will leave this issue open as a storage for the Markdown-related ideas. 

I do hope that we will try to implement it in this fall. If you have any suggestions - feel free to share them here.

**Comment by mattie47** [comment]
Just curious - but what kind of thoughts and ideas were you after? 

Input on how other tools have implemented the support, or design considerations etc? 


Thanks

**Comment by eapyl** [comment]
It would be great to have support of markdown in 'New post' editor:
![image](https://user-images.githubusercontent.com/1629511/45595312-eb1da400-b9a9-11e8-9eb7-b54bc0283914.png)
So it will be possible to add new posts just improting markdown text. And it means there will be import/export functionality.

**Comment by bobmitro** [comment]
End of this year we should have a implemented a new Markdown editor. I can not promise, only time will tell, but I think this is a real date.

**Comment by mattie47** [comment]
Thanks for that feedback.

I've spent a bit of time looking at different markdown options with different static sites, and thought it might be worth sharing my 2 cents on it.

**1. Converting content to markdown**

You might want to have a look at other static site generators such as Ghost. Everything Ghost does is in markdown, and like Publii, it has a wordpress importer.

I found it oooookay at doing this.

**2. User experience of markdown**

Some tools do this well, some do it badly. Personally, I absolutely love the editor you simply have within github for this. The primary benefits are mostly in the shortcut keys, and the simple ability to paste an image and have it auto upload. 

I've also looked at a number of off line markdown options, and thus far Typora would have to be the best editor I've come across. Personally I'm still mostly using OneNote for everything with blog content creation, but if Publii supported MD I would probably move to Typora as it's such a nice editor to use :-)

**3. Integration with existing content**

I suspect one of the hard challenges for implementing markdown support, is simply the nature of supporting existing content. 

i.e. Do all current posts a user have get converted to markdown? Personally I think no as there are too many challenges around that, and markdown isn't a 'one-fits-all' solution. 

The challenge in my mind would be hybrid posts. I.e. Is a mixture of content and html created in the normal editor supported in-line with markdown?

Perhaps have a look at how Wordpress do this...I seemed to think you can with WP...



**4. Will there be an option to export all posts as markdown?**

I've been enjoying recently looking further into using Publii for blogging. However as a millennial, I struggle to commit! 

If you do implement markdown support, a really nice feature would be the ability to export all [supported] posts with markdown syntax as md files. 

I imagine it'll help others breath easy knowing they're not locked in with Publii should they wish to use their content elsewhere later. 

I guess this is probably the benefit of other tools such as Hugo, were you literally write your posts in markdown, and the source files are in fact what then generate the website. It really is quite nice - so why am I not using it? 

The reason why I'm more attracted to Publii is because the out-of-the-box experience means I can more quickly get creating rather than literally generating a site from scratch. I spend all day at work in a command line, and the last thing I want to do at home as spend more time in a command line! ;-)

Thanks,

Matt

**Comment by Orcomp** [comment]
Just discovered Publii and it nearly ticked all the boxes... except content format and storage. Storing content in SQLite is a no go for me. Markdown or Asciidoc flat files is critical. Will use MkDocs for the next few months but will keep a keen eye on Publii.

**Comment by Swader** [comment]
@dziudek @bobmitro any news on this? End of year has come and gone.

**Comment by bobmitro** [comment]
HI Bruno,
We have reviewed our plans and priorities for this year, and I'm afraid we're letting it go.

**Comment by Swader** [comment]
Shame.

Note that one approach to make this happen easily and without BC breaks is by adopting the method Ghost used: introduce a new element "Markdown content" into the WYSIWYG editor. This way, you add MD content into that element and the renderer renders the MD as usual HTML when processing, but you don't break previously existing posts because they simply didn't have this elements. Here's a demo:

![ghost](https://user-images.githubusercontent.com/1430603/51030059-890c2e80-1598-11e9-8192-4bf979eb1713.gif)

Is there any way to help? Can we see the public roadmap? Did you consider some Gitcoin bounties for external contributors?

**Comment by dziudek** [comment]
@Swader - after our analysis, proper implementation of Markdown needs a big core changes. At this moment we have not workforces for such a big task. In fact to properly implement Markdown support we should implement a different kind of storage for data, what affect literally all elements of Publii. It will also lead to a backward compatibility issues etc.

Please remember that some markdown shortcuts are working in our editor since the 0.31.* release:  https://github.com/GetPublii/Publii/issues/166

**Comment by Swader** [comment]
It's more a matter of supporting community contributions of content for one's blog. Markdown is easier to version control and maintain, and helps with efforts like [The Explainers](https://github.com/status-im/the-explainers) where people submit content and it gets peer reviewed, but is then easy to import into any CMS. Publii disqualifies itself from such efforts because it is neither multi-user, nor markdown friendly, making collaboration incredibly difficult. We could use HTML source and import sources generated from the markdown, but that's a workaround I'd rather not have to make.

But I understand that it's a technical undertaking you have no capacity for at the moment, so won't push further.

**Comment by dziudek** [comment]
@Swader - yes, we know that lack of Markdown support is a pain in some situations. That's why we are not closing for adding support for Markdown in the future. But at this moment we have more important tasks to do like file manager or ability for multi-user work based on SQLite (I am currently exploring this topic). 

That's why this issue will remain open - in the longer perspective Markdown support will be one of our big milestones :)

**Comment by bobmitro** [comment]
Hi, 

I have just published a complete Publii's roadmap for 2019
https://getpublii.com/find-out-whats-on-publiis-roadmap-for-2019/

**Comment by Swader** [comment]
YAY! ❤🎊🎉🎊❤

**Comment by jeremydouglass** [comment]
Nice idea. This would also be a great feature to support migrations other than WordPress.

Lots of SSGs are build around markdown content, and lots of people who are interested in SSGs are like writing in markdown....

**Comment by Swader** [comment]
This feature has become a deal breaker for me. I am unable to check spelling in the Publii editor, and I can't write elsewhere and just paste content in unless I do full-on HTML and then use only the HTML source view. It's the same when trying to work with other people on common content. It's impractical and clumsy. I love the themes I purchased so far and the CMS has saved me more trouble than I would have had otherwise, and I don't regret my OC donations but at this point the lack of markdown prevents me from working on content with other people and hinders me more than helps my productivity.

**Comment by dziudek** [comment]
Hi @Swader - yesterday we have published for download Publii v.0.36 which has a built-in Markdown editor. The official news will be published soon :)

**Comment by GetPublii** [comment]
Have you tried a fresh Publii 0.36 release? It comes with Spellchecker and is "armed" with a SimpleMDE editor.
https://getpublii.com/download/

**Comment by dziudek** [comment]
One thing - unfortunately spellchecker is not working in Markdown editor due its architectural limitations, but works in the block and wysiwyg editor.

**Comment by Swader** [comment]
lol what a coincidence.
Testing now, thanks! Spellchecker missing is OK because MD support means I can write anywhere, like in hackmd or VScode
