### ISSUE TITLE
Contributing Guidelines

### ISSUE THREAD

**Issue by crock** [GetPublii/Publii#1177]
I would like to contribute to the core codebase in some way, but I can't find any public contribution info. Are you actively accepting new PRs for feature additions? Should I open an issue first with a feature proposal?

**Comment by dziudek** [comment]
Hi,

At this moment we handle our internal list of features to implement (because Github does not meet our needs for this purpose - we use it it mainly for communication/bug/feature reports with users now), so if you have a plan to prepare some feature, firstly I suggest to create a feature proposal and wait for accept of it. Because implementation of such feature can collide with our plans, be redundant or just can be rejected from other reasons.
