### ISSUE TITLE
[Bug]: Can't build Publii

### ISSUE THREAD

**Issue by kosssi** [GetPublii/Publii#1178]
### Operating system

Ubuntu 20.04

### Publii version

master

### Post editor

None

### Bug description

I would like build Publii on my laptop to contribute on this wonderful project but I have always the same error when electron display post page:

```shell
DB error Error: The module '******/Publii/app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 106. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

### Steps to reproduce

```shell
$ nvm use
Found '******/Publii/.nvmrc' with version <v16.13.0>
Now using node v16.13.0 (npm v6.14.18)

$ npm i
...

$ (cd app && npm i)
$ npm run dev
```

I open another shell:
```shell
$ nvm use
Found '******/Publii/.nvmrc' with version <v16.13.0>
Now using node v16.13.0 (npm v6.14.18)

$ npm run build
```

### Relevant log output

```shell
$ git log -1
commit f59806b73a05753fc458fc15be8e93785ec09386 (HEAD -> master, tag: 0.41.1, origin/master, origin/HEAD)
Author: Tomasz Dziuda <tomasz@dziuda.com>
Date:   Mon Nov 7 12:17:32 2022 +0100

    chore(version): bump version to 0.41.1
```

**Comment by dziudek** [comment]
Hi,

Please try to do: https://github.com/GetPublii/Publii/wiki/App-build-process#keytar-sharp-and-node-expat-node-modules-compilation

BTW If you want to contribute something bigger than bug fix, I suggest to start with feature proposal, because your PR can be redundant/colliding with our current work or just can be not accepted for other reasons - so to avoid unnecessary work it is worth to plan it properly :) 

Also please remember that the most up to date version of the app is currently on this branch: https://github.com/GetPublii/Publii/tree/v.0.42

**Comment by kosssi** [comment]
Thanks, it's exactly that!

I would like create new block on the editor when I have the time, just for test it ;)
