### ISSUE TITLE
Ability to download example websites and import them

### ISSUE THREAD

**Issue by mattie47** [GetPublii/Publii#119]
Hi there!

I discovered Publii tonight while looking for static site generators, and thus far it seems pretty cool!

I like how easy it is to jump right in and start trying stuff, given it can all be done client side. 

Anyway - So I've spent the last couple of hours trying to get my head around how to build a site's structure etc, and it would be really nice if as a user I could simply import the demo sites provided in the market place. 

The demos have a nice layout and structure, and being able to see how this is all done within the publii client would really help new users. 

**A few other comments:**

1. Markdown would be fantastic. 
2. Code syntax highlighting (Yes there's the code option, but with markdown you can specify language etc for highlighting)
3. Where can I find a list of available post editor shortcut keys (I've looked through the docs). 
4. One thing I love about github's editor is the ability to easily paste screenshots from the clipboard. I noticed I can paste stuff I've written with OneNote including images into Publii, however strangely I couldn't post images from the Windows clipboard (copied via snipping tool). 

Thanks!

Matt

**Comment by pagelab** [comment]
> it would be really nice if as a user I could simply import the demo sites provided in the market place.

I think this would make it even more easy for a less seasoned user to quickly bootstrap a site with Publii, helping them achieve good results with less effort.

Just some quick suggestions of configs and data that could be imported – or predefined somewhere in the theme:

* Preset structure for a particular type of site,
* Recommended options and configs,
* Predefined posts with layouts following the site structure (a more marketing oriented front page, other with post listings, and another containing an working contact form),
* And so on...

By offering sane defaults, theme developers can better educate users about the theme's purpose and scope ("learn by example" kind of thing).

**Comment by bobmitro** [comment]
Hey,
Thank you for your suggestions. We will try to implement/add as many of them as possible.

1. We will deliver the demo sites; 
2. We have a plan to add a markdown editor this year, this is not easy because we have to take care of the migration process from WYSIWYG and vice-versa
3. Code syntax highlighting  would be added the next theme's release
4. All available free themes are just for a good start and understanding how they work; you can develop almost any kind of themes with more advanced layout or options. From this month we will start to develop one new theme per 1-2 months undoubtedly more attractive.
5. Bootstrap is good if you need to get a prototype, when you don't have enough time and want to build something quickly. For production, you should use dedicated, custom CSS/JSS to keep the website lightweight and fast. Bootstrap 4 with minified files comes with a total at around 200 Kb - this is absolutely not acceptable especially when we build the static site that naturally should be super fast; for example, our homepage excepting image files weights 58 Kb only (https://tools.pingdom.com/#!/dEIoFh/https://getpublii.com/). This is why I do not prefer to create themes based on Bootstrap.

**Comment by mattie47** [comment]
Hi @bobmitro,

Thanks a lot for the detailed response. It was much appreciated.

I'm still exploring usage of Publii, and it definitely has a lot of potential :-) 

I've spent hours looking at Hugo/Ghost/Grav/Jekyll and I've liked the out-of-box experience of Publii the most. 

Re. delivery of demo sites - just curious if this has been done?

Re. code syntax - I'm assuming you're referring to: https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html or has there been another/different update?

Thanks,

Matt

**Comment by bobmitro** [comment]
Hi Mattie,
Sorry for the delay, I will deliver the demo soon - back from vacation - too slow :)
I'm not sure it is a good idea to add the code syntax highlighter to all themes. I've added last time an [article](https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html) how to do that - it's easy.

**Comment by mattie47** [comment]
For anyone curious - there's an example of TechNews you can download here: https://publii.ticksy.com/ticket/1697140/

**Comment by GITchristoph** [comment]
Hi @bobmitro 

May I pick this one up and ask if you already offer the demo-themes for download and where?

It would be helpful to get started ;-)

Greetings, Chris

**Comment by GITchristoph** [comment]
Hi @bobmitro 

May I pick this one up and ask if the complete demo sites are now available and if yes, where?

it would be very helpful to get started with Publii with a demo site.

Thanks for any hint in advance,

Chris

**Comment by bobmitro** [comment]
Hi, 
I gave up on it. 

**Why?** 

Delivering content demo is connected with additional work and constant care for updates: the themes and the demo packages. 
We are a small team and develop Publii without any profit, this is why we can not yet give you full support.

Unlike other CMS and the tedious process of setting up your, site Publii comes with a simple theme system: you have a blank page because you just have to publish some content (post). That's it. Your website will be built automatically when you deliver content.

**Comment by pirinoa** [comment]
> Hi, I gave up on it.
> 
> **Why?**
> 
> Delivering content demo is connected with additional work and constant care for updates: the themes and the demo packages. We are a small team and develop Publii without any profit, this is why we can not yet give you full support.
> 
> Unlike other CMS and the tedious process of setting up your site, Publii comes with a simple theme system: you have a blank page because you just have to publish some content (posts). That's it. Your website will be built automatically when you deliver content.

Hey there. Thanks for Publii... just discovered your app while looking for SSG's for Designers.  I was hoping for some demo content too but understand you have limits. The CMS looks amazing and you deserve so much bigger audience. Thank you all! 🫶🫶
