### ISSUE TITLE
[Q]: development status / the future of publii

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1243]
### Feature Description

it appears development has slowed markedly over the last 3 years and so i'm wondering if @GetPublii and the contributors are still passionate about this project

**Comment by bobmitro** [comment]
Hi,

I'd like to assure you that Publii is very much an active project that we're continually working on.

While it's true that Publii started as a relatively basic tool with limited options, it has evolved to become a nearly complete blogging platform. Our primary focus at the moment is on extending its capabilities through plugins. We are about to release a new version of Publii, along with several exciting plugins that will enhance its functionality.

I understand you may have concerns about the direction of the project. To clarify, we are not planning to move towards becoming a page builder or anything of that sort, as there are already multiple established tools in the market for those needs. We aim to excel in the niche we have carved for ourselves, rather than trying to be a "jack of all trades."

Also, please bear in mind that Publii began—and continues to be—a side project for us. Despite that, we are committed to maintaining and improving it.

**Comment by atomGit** [comment]
hi bob - thanks for the response - i'm glad to hear things aren't stalling
