### ISSUE TITLE
[Bug]: Internal author link doesn't work

### ISSUE THREAD

**Issue by Krotosz6** [GetPublii/Publii#1614]
### Operating system

Ubuntu Studio 24.04, KDE Neon 6.0.

### Publii version

0.46.0.

### Post editor

None

### Bug description

Links directing to authors no longer work. WYSWIG and Block editor finds these subpages and allows you to select them, but then when you click on them, you don't see them. When generating the page, they are not turned into proper links, and they exist as:

https://example.com/#INTERNAL_LINK#/author/example

**Comment by dziudek** [comment]
@Krotosz6 - to be honest as I have checked it has been broken also earlier (at least in v.0.45.2), so this bug is not introduced in v.0.46 as your description could suggests

Thank you for finding this bug - I will fix it and prepare hot-fix release in nearest days - I will let you know when such release will be available

**Comment by Krotosz6** [comment]
Sorry for the incorrectness. I don't have a lot of these links on the site, so I didn't notice before. I'm sure it used to work. I think about six months ago. Today I was updating Publii and noticed this bug just after this. That's where the misunderstanding came from.

**Comment by bobmitro** [comment]
Please make sure to download [build 16904](https://getpublii.com/download/) as it should work ok now.

**Comment by Krotosz6** [comment]
It work. Thanks
