### ISSUE TITLE
[Feature Request]: Please add "Font Size" to the TinyMCE editor used for the WYSIWYG editor

### ISSUE THREAD

**Issue by bjazmoore** [GetPublii/Publii#1691]
### Feature Description

Font size is a core toolbar element supported by TinyMCE.  Publii could support it by coding the style inline within a <Span> tag.

From the TinyMCE website:
![1](https://github.com/user-attachments/assets/aae4301e-c82e-41f7-99f1-0babca87116e)

It would make sense to support this in the Blocks editor.  I do not know what the underlying technology for the blocks editor is though, so unsure if this would be supported.

**Comment by dziudek** [comment]
@bjazmoore - you can add any TinyMCE core features using available API: https://getpublii.com/dev/how-to-add-custom-config-or-js-for-post-editor/

Such feature is not good, because font size should be modified by usage of different styling not `style` attributes, because it can break visual compatibility when switching themes. That's why it is not available by default
