### ISSUE TITLE
Dark theme for the UI

### ISSUE THREAD

**Issue by gnppn** [GetPublii/Publii#183]
Hi,

It would be nice to have the option of a dark theme. OSes are (finally) jumping on this train, Publii should also get one. :)

Thanks in advance!

**Comment by dziudek** [comment]
Hi,

We will consider this, but at this moment I cannot provide any ETA for that - we have a lot of more important this to do in the next 3-4 months :( Preparation of the dark theme will be probably time consuming as there is a lot of things which we have to consider from the UX view, especially in the post editor.

**Comment by garret-linn** [comment]
Building on this idea
I would be happy to see the tool menu on the left (the big blue thing)
to have that be able to change color per website

you already have a color assignment for the author icon (pizza)

it would be great to use that color - per web site
so that I have a different color per web sitye for the tool menu in the App

thanks

**Comment by dziudek** [comment]
(clearing the backlog)

**Comment by Doyoulikemilk** [comment]
Hiya On the opposite I dislike Dark mode but how could I close the dark mode? Thank you!
