### ISSUE TITLE
Untie blog (index.hbs) from homepage

### ISSUE THREAD

**Issue by pamtbaau** [GetPublii/Publii#217]
Currently Publii is very much blog oriented, like Wordpress used to be. Like with Wordpress it would be nice to have an extra site or theme option to indicate which post should be shown as frontpage and which menu item points to the blog (if a blog is used at all...).

Wordpress uses the following setting to indicate that the homepage/frontpage is post 'Home' and the blog page is not assigned to any page:
![image](https://user-images.githubusercontent.com/5120011/49587174-73856280-f963-11e8-9d92-c82c54391999.png).

Currently I use a workaround by assigning a single post as being 'Featured' and use that post in the 'index.hbs' which handles the found featuredPost very much like the 'post.hbs'. And I assign the frontpage to the menu item 'Home'.

**Comment by guyou** [comment]
The starter theme has a Hero section. So we can probably simply add an option to inhibit the blog list on the index to achieve this.

**Comment by nekohayo** [comment]
I spent a few hours trying out Publii, to see if it could fit my (fairly simple) static personal home page (not blog) needs, with the default ("Simple") theme, and I was kinda bummed out by this too.

In my test case, I wanted to have a nice "hero image" section on the homepage with only one header and/or paragraph, and then the rest goes below the image, because the image I'm using is not suitable for having all the text paragraphs being in the "hero" section.

The main conundrum I encountered was that there's this confusing option in the theme's "Layout" section that says: "Front page displays:  (o) Latest posts  ( ) Selected post", where
* If you use "Front page displays posts" you have the flexibility to put some text paragraph in the hero section (through the theme settings) but there's this big obnoxious empty white section below the hero area, that serves to automatically show the latest posts' excerpts, and if you have no posts that you want to show there then it remains visible and "looks broken".
* If you use "Selected post" you can't have text other than the post title in the hero section (and you can't disable showing the title in the hero section either!), so if you just want a paragraph of text in there you can't use that option...

The workaround/hack that got me closest to my goal was to create a "Welcome" post in which I put some content, and individually mark ALL the other posts as "Exclude from homepage". But even then, it doesn't solve the problem, there are a couple more problems with that approach:

* It's a "post" so it will show up in the syndication (RSS/Atom) feeds
* It forces showing its title when it gets embedded in the front page
* It only shows an exerpt of the post (the first 3 lines), so you can't actually have meaningful content in there.

So with all that said, currently there seems to be no way to have a static content front page that simultaneously allows having some flexible static content in the hero section AND below it (or "nothing at all").

**Comment by bobmitro** [comment]
It's completely out of the Publii app, all your issues are more about the theme and its settings. What can I suggest - adjust the theme to your needs or create the new one.
