### ISSUE TITLE
Distracting useless effect in editor

### ISSUE THREAD

**Issue by Pilvinen** [GetPublii/Publii#266]
Please, remove this horrible effect:

https://snag.gy/grUdfM.jpg

1) It blocks the text that I'm actively trying to view.
2) It serves no real purpose.
3) It's distracting and bad user experience.
4) I'm 99% sure you can't find a single end user who loves it and wants to keep it.

**Comment by internettips** [comment]
I vaguely remember seeing something like that around the Christmas break time, but to be honest, until you mentioned it, I didn't really notice. Though that functionality might provide another way for Publii to provide alerts, make special offers available, etc. Maybe they were testing.

**Comment by Pilvinen** [comment]
What? No, I'm talking about this:

https://snag.gy/3fTUlF.jpg

The screenshot if from the v0.32.4 that is available for download on the Publii website.

**Comment by bobmitro** [comment]
@Pilvinen Thanks or your feedback. This is a remnant of the previous version (this one before the December edition) Since we started working on the editor's tuning, we have quite similar feelings. 
It has been removed in this commit: https://github.com/GetPublii/Publii/commit/b0a7f08dd286547c1b69bf2e76615121603531ef
