### ISSUE TITLE
Vertical cursor movement creating new <p> blocks in middle of <pre> blocks

### ISSUE THREAD

**Issue by dullroar** [GetPublii/Publii#281]
This is with Publii v.0.32.4 (build 11275) Beta. Type in the following three lines:

This is some preformatted code.
This is some more.
And some more.

Highlight them and change their format to `<pre>` using the menu (or in the raw HTML). Now position your cursor at the head of the line that reads "This is some more." Hit the down arrow. That is creating a new `<p>` element between "This is some more." and "And some more." Following is what is shown in the raw HTML:

```html
<pre>This is some preformatted code.<br>This is some more.</pre>
<p> </p>
<pre>And some more.</pre>
<p> </p>
```
This is consistently reproducible. The up arrow doesn't seem to do anything, but the down arrow with `<pre>` blocks on the page will not just create one `<p>`, but multiple, if you keep trying. For example, once the split above occurs, if I down arrow towards the newly created `<pre>` block, once I reach it, it keeps inserting new `<p>` blocks ahead of it. Very strange behavior.

**Comment by dziudek** [comment]
Hi,

This issue has been fixed some time ago: https://github.com/GetPublii/Publii/issues/242

It will be solved with the next version of Publii.

The only issue which can still exists can be connected with the last pre element which have no elements after. It is caused by fact that in other way there was no way to add any other elements after the last pre tag.
