### ISSUE TITLE
Feature request: allow override of post date to be entered as text

### ISSUE THREAD

**Issue by dullroar** [GetPublii/Publii#282]
I am trying to bring in an existing site, and for that reason am overriding the post date on virtually every post. The date/time picker, while ensuring accuracy and probably sidestepping issues like locale-specific date formats, is very cumbersome for this.

I would like to just enter a date (and have the time default to midnight if not given, or current time as second-best option), and if Javascript's `Date` constructor can make sense of it according to my locale, all is good.

**Comment by dullroar** [comment]
Something like the control here - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by dziudek** [comment]
As I have mentioned in your other issue - we know about the problem with 12-hours mode - it will be fixed in the next version.

At this moment I do not see any sense of adding date as text. Especially due fact that the text must be parsed into timestamp and allowing users to provide any date in any text form would be extremely problematic.
