### ISSUE TITLE
No Google fonts as default source - GDPR

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#361]
I suggest to deliver the fonts locally/somehow else. The default delivery via Google Fonts is risky with respect to GDPR.

**Comment by bobmitro** [comment]
To be in compliance with GDPR regulations you can always give an appropriate message in your Privacy Policy. We do not serve fonts locally, because it requires a big "management system", especially when the themes comes with a set of a dozen fonts. 
You can always change it on your own.

**PS: this repo is dedicated to Publii app; to report any issue or get support for themes, please use https://publii.ticksy.com/**

**Comment by GiantCrocodile** [comment]
It's not guaranteed that an appropriate message is enough to be GDPR compliant because the data transfer happens already on first page visit, while the visitor is not seeing/accepting the proper message prior. This topic is under heavy discussion by privacy officers.

The main reason for this issue is: Any software's default installation and configuration should be GDPR compliant or at least warn you regarding this problematic situation. Right now, none of the both options is given.

**Comment by bobmitro** [comment]
With the advent of Publii v.0.39, all fonts are now delivered locally. More about it: 

- https://getpublii.com/docs/fonts.html
- https://getpublii.com/blog/release-039.html
