### ISSUE TITLE
Add Armenian HTML Language Code

### ISSUE THREAD

**Issue by bobmitro** [GetPublii/Publii#366]
<html lang="hy">

**Comment by dziudek** [comment]
Instead of handling all possible HTML language codes in the future (what can lead to an extremely long list of options), I have added an option "Custom language code" which shows additional input field for any language codes which are not listed in the dropdown:

![Screenshot 2019-03-11 at 14 50 42](https://user-images.githubusercontent.com/22004/54128858-44243d00-440d-11e9-8ccd-aa35df2fb496.png)

Also if the user will use existing language code e.g. "pl" in the "Custom language code" field - it will be replaced to an existing option after coming back to the settings view.

No themes changes are required for this modification - we are still using the currentSite.config.language field as before - are custom language code detections are done by the settings view.
