### ISSUE TITLE
Javascript error when switching to website

### ISSUE THREAD

**Issue by Areahints** [GetPublii/Publii#378]
applied latest update, i have 4 sites, decided to switch to one, this error pops out

```
Uncaught Exception:
SqliteError:no such table: posts
    at Posts.load (/opt/Publii/resources/app.asar/back-end/posts.js:30:24)
    at App.switchSite (/opt/Publii/resources/app.asar/back-end/posts.js:221:26)
    at EventEmitter <anonymous> (/opt/Publii/resources/app.asar/back-end/events/site.js:277:38)
    at EventEmitter.emit (events.js:182.13)
    at EventEmitter.emit (domain.js:442.20)
    at WebContents <anonymous> (/opt/Publii/resources/electron.asar/browser/api/web-contents.js:285:13)
    at WebContents.emit (events.js:182.13)
    at WebContents.EventEmitter.emit (domain.js:442.20)
    at WebContents.toplevelDomainCallback (domain.js:121.23)
```

unsure how to proceed...

**Comment by dziudek** [comment]
Hi,

The error appears every time for every website? Also - on which platform this error appears?

I cannot reproduce this issue on macOS and on Windows.

**Comment by Areahints** [comment]
only for one of the sites, the remaining 3 opened fine

OS is linux ubuntu 18.04

**Comment by dziudek** [comment]
I suppose that the database file can be corrupted - can you share the non-working website backup (you can just archive the site directory manually). If you do not want to share it publicly, you can send a private ticket on ticksy - https://publii.ticksy.com/

**Comment by Areahints** [comment]
[agroconscious.tar.gz](https://github.com/GetPublii/Publii/files/2983542/agroconscious.tar.gz)

**Comment by zybex86** [comment]
Had similar problems on a different cms but that caused me loosing a whole lot of data because of it and the admins couldn't get my data back... This needs to be sorted out IMHO as can cause a lot of problems for ppl

**Comment by dziudek** [comment]
@Areahints - as I see the db.sqlite file is empty - unfortunately the only way to restore data is use the rendered preview to regenerate the content or backup if you have created a one.

I have never saw this kind of situation before, I suppose that it can be caused by some file write issue. Maybe the new library `better-sqlite3` have some bugs or it is an OS/permission related problem. 

@zybex86 - totally agree and we always take seriously handling of any DB-related issues, and that's why we have implemented in Publii the backup mechanism. Fortunately this kind of issues are rare, but always we are trying to find out what is a reason of the problem to minimalise the risk of data lost.

@Areahints - if you remember any details which can help to investigate a reason of this issue - please let me know.

I will left this issue open as I will do a research of potential reasons of this problem.

**Comment by zybex86** [comment]
Sorry but their problem was that I had two templates - old and new. When I created the new template the database probably just used the old one instead of creating a new database (as the new view had different pages from the start) and thus when I deleted and EMPTY blog page (that could choose which blog database to connect to) I lost an entire database of blog posts from the old view. If you know anyone working with EduPage then you can maybe ask them what was the issue
