### ISSUE TITLE
Theme folder missing from the docs?

### ISSUE THREAD

**Issue by cfv1984** [GetPublii/Publii#496]
Hi! I tried to create a new theme following the docs, and can't find where I should put my local theme for development, or how the development workflow... well... works.

Can anyone please lend a hand with this? It's a pretty high-value feature for us newcomers.

**Comment by bobmitro** [comment]
Hi,
Basically, Publii theme requires 7 files to exists, but you can also attach other files.
Here is a list of required files:

1. **config.json** - main theme configuration file,
2. **index.hbs** - front page template,
3. **post.hbs** - single post template,
4. **tag.hbs** - single tag page template,
5. **author.hbs** - single author page template,
6. **thumbnail.png** - that will be displayed in the application settings (required dimensions: 400x300px or 800x600px),
7. **assets/css/main.css** - main CSS file which is used to generate the styles.css file (which is merged with the optionally-generated visual-override.js and Custom CSS via “Custom CSS Tool”).

For better file organization we can also use the partials folder with files that may be called directly by other files:

- partials/ - location for files which will be loaded with use of the {{> fileName}} code,
- partials/**footer.hbs** - footer used in all pages,
- partials/**header.hbs** - header used in all pages

### Preparation of the environment
First, create a new website, then, close the app. 
Go to the **Documents/Publii/themes/** and create a folder that will be a boiler for your new theme files - call it as you are going to name the theme ( in our case: blank)
Now create all of the required files mentioned at the beginning of this short guide.

**REMEMBER**: the files cannot be empty - otherwise, the page does not render (add comments or something else)

The structure of your theme files should look like:
```
- assets
- css
  main.css
- author.hbs
- config.json
- index.hbs
- post.hbs
- tag.hbs 
- thumbnail.png
```

### Configuration of theme
Before we start playing with pages, we need to configure some main theme settings.
To name the theme and configure basic parameters open the config.json file and put there the following code:

```
{
    "name": "Blank",
    "version": "1.0.0.0",
    "author": "TidyCustoms <https://tidycustoms.net/>",

    "config": [

        {
            "name": "postsPerPage",
            "label": "Posts per page",
            "value": 15,
            "type": "number"
        },
        {
            "name": "tagsPostsPerPage",
            "label": "Tags posts per page",
            "value": 15,
            "type": "number"
        },
        {
            "name": "authorsPostsPerPage",
            "label": "Authors posts per page",
            "value": 15,
            "type": "number"
        },
        {
            "name": "excerptLength",
            "label": "Excerpt length",
            "value": 25,
            "type": "number"
        },
        {
            "name": "logo",
            "label": "Website logo",
            "value": "",
            "type": "upload",
            "upload": true
        }
    ]
}
```
What have we done? We called the theme “Blank,” specified a version and author’s theme, determined how many posts should be displayed on the index, post, and author page and how many words will contain excerpt. The last option “logo” is needed to allow users to upload a website logo.

The last step to run our website with the new theme:  launch Publii once again, go to the Settings -> Basic Settings and select from the list your “Blank” theme and Save Settings. 
Now your new website will use the “Blank” theme. 

**What next?** 
Now you have to focus on the coding aspect of your new theme. Take any free theme and see how it's built.

**Comment by cfv1984** [comment]
Awesome! Thanks
