### ISSUE TITLE
Use of Lunr.js or Elasticlunr.js instead of Algolia or Google

### ISSUE THREAD

**Issue by paulocoghi** [GetPublii/Publii#556]
I saw the issues #120 and #140 suggesting the implementation of Algolia as a replacement for the Google search.

But I would like to suggest a **simpler** approach: [Lunr.js](https://lunrjs.com/) ([github](https://github.com/olivernn/lunr.js)) or [Elasticlunr.js](http://elasticlunr.com/) ([github](https://github.com/weixsong/elasticlunr.js))

In short, it is a completely free method (using an open source js library) that can be integrated natively on Publii and allows visitors to do searches directly on the front-end, without relying on other external services like Algolia or Google.

The index can be rebuild on Publii itself, every time the site's author rebuild the site (and/or make new changes on it).

Then, the index file (JSON) will be published together with the site's files. Thus, every search will use this index file, that will be downloaded on the visitor's browser only once per version and only when the visitor makes a search.

It doesn't compromise the site's time to load and makes subsequent searches near real-time, as well as available offline.

---

_**Elasticlunr.js** is faster and smaller (18 KB minified and 5 KB gzipped), and generates even smaller indexes (about half the size) compared to Lunr.js._

**Comment by ajeet001** [comment]
They intend to use flexearch. I am not sure when .
https://publii.ticksy.com//ticket/1991767/
There is also a comparison among lunr, flex, and elasticlunr here: https://github.com/nextapps-de/flexsearch

**Comment by lrq3000** [comment]
Devs, please implement a local search as an option (some people may want to keep Google search since it allows for other options such as image search).

I think it should be very simply to hack something quickly using lunr.js or elasticlunr.js by using the feed.json as the database file, it already has all posts content in a neat JSON structure. Of course, Publii devs may want to do something more reliable than relying on the RSS feed file, but if anyone would like a quick solution in the meanwhile, this may work out nicely.

If someone would like to give it a try, I've found this interesting tutorial (not for Publii but should be easy to adapt): https://sentamal.in/articles/static-site-search-with-lunrjs/

**Comment by paulocoghi** [comment]
@lrq3000, I am not a dev contributor to Publii, but I also suggest `flexsearch` instead of my previous suggestions _(Lunr or ElasticLunr)_.

Flexsearch is as easy as Lunr/ElasticLunr, but a lot faster than both.

I believe that Publii needs more attention, to grow its community and receive more contributions from other devs outside the core team, enabling the development of new features like this one.

**Comment by bobmitro** [comment]
You can now use our new [Static Search](https://marketplace.getpublii.com/plugins/static-search/) plugin based on FlexSearch.
