### ISSUE TITLE
Fail to link CSS and JS files with my server configuration

### ISSUE THREAD

**Issue by antoninadert** [GetPublii/Publii#649]
I use the below server configuration on Mac OS: 
Relative URLs, manual upload

My problem is that the CSS and JS never load from the index.html, leading to this kind of display:
![image](https://user-images.githubusercontent.com/8929314/72220408-ab8cab00-3550-11ea-9725-8f240d59d023.png)

The problem is reproducible with **relative URL** value as `/` . I corrected it by replacing `/` by `./` so it seems to be a problem with relative paths on macOS / linux I guess.

**Comment by Goozoon** [comment]
I think this is the same problem i have: #664

When you Use server setting for Sync (e.g. http://www.aaa.com)
then all URL are generated correctly. like: data-src="http://www.aaa.com/media/posts/1/Home.png

When you try to set Relative URLs, then all is wrong :(
instead of
<img src="media/posts/1/Home.png"

we are getting:
<img src="/media/posts/1/Home-Studio711.png"
