### ISSUE TITLE
Changing "sites" location empties target folder without warning

### ISSUE THREAD

**Issue by antoninverrier** [GetPublii/Publii#682]
Using Publii version v.0.35.3 (build 12104) Beta on Windows

I'm storing the "sites" directory on a server to able to work on different computers. "site location" in global settings in something like "\\server\users\me\publii\sites"

Today, I'm setting up Publii on a new computer. It doesn't let me save the global settings if no site has been created yet (the "save settings" button does nothing). So I create an empty site, change the "sites location" in global settings and hit "save settings".

Now my network folders only contains the empty site I've just created, the others sites that existed in the folder are gone, without any warning.

I'm under the impression that what I've done used to work in the past, and that Publii just used to find the existing websites in the folder instead of wiping everything. Am I remembering wrong?

If this is intended behavior, it would be nice to have a warning that the target folder will be wiped and the ability to cancel.

**Comment by dziudek** [comment]
Hi,

The problem with saving settings when there are no website should be fixed in Publii Prerelease 0.36.

Regarding folder clean up - the behaviour did not changed as it is used to prevent a problems with treating other folders as sites which can lead to unexpected results.

I will add an additional warning during save that the destination folder will be emptied.

**Comment by dziudek** [comment]
Warning added :)

**Comment by cristian-milea** [comment]
I am a little bit confused. 

How can I complete the Publii <-> Dropbox flow if I get my folder cleared every time I add a new user to it?
