### ISSUE TITLE
Automatic backups

### ISSUE THREAD

**Issue by a-zurcher** [GetPublii/Publii#707]
Would it be possible to have an automatic backup feature? as there's now Publii daemon, maybe it could be activated as soon as a certain date has passed and the user opens the application?

**Comment by j0el** [comment]
What I would like is to maintain my web sources  with git.  That has a few advantages.
1.  I could fork to try new things without having to make copies.
2. I could easily work from two or more computers
3. Backup would be  simple and space saving and I could keep my main repo on a few different places (github, AWS codecommit, etc)

**Comment by dziudek** [comment]
We do not consider such feature at this moment, because it can be solved in many different ways as Publii is a desktop app which stores data on your computer.
 
So for example - if you have regular backups of your disk where Publii stores wbesites -> you have also backups of your Publii websites :) 

Also creating backups in Publii is very simple so if you need backup before critical changes - it needs few additional clicks.

**Comment by j0el** [comment]
I understand.  I do take backups.  My use case was when I am not at home,
say I am on a cruise and I want to post some photos and blog entries.
Using git would reduce by a lot the amount of data I need to transfer to
get up to date.  But of course I can backup to dropbox or S3 and then
download to my travel laptop and publish.

I hope you do not mind suggestions even if you do not agree with them.  I
am very pleased with Publii overall.

**Comment by dziudek** [comment]
@j0el 

> I hope you do not mind suggestions even if you do not agree with them.  I am very pleased with Publii overall.

Feel free to provide any suggestions - we just need to choose the most important ones to implement, and in this case I see that the problem can be solved in a different way, so we can focus on other things :)
