### ISSUE TITLE
The 2 little bugs with v.0.36.0 (build 13213) beta

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#736]
![image](https://user-images.githubusercontent.com/5204724/84148921-df311a00-aa89-11ea-9730-8bcbf2ef3fef.png)

1. Under KDE (at least Debian) installed via the .deb the icon is not working (top left)
2. English International is not supported while any other English is supported by the spellchecker
3. Forget the current theme, the issue was in my override ~~don't show the version with TechNews (but work with Tattoo)~~

**Comment by dziudek** [comment]
1. The issue with icon should be fixed in the next release
2. Unfortunately it seems that "en" is not available in spellchecker for your linux instance. In this case you have to select a english version which supports spellchecker. We cannot decide that if you select "en" then spellchecker will be set to "en-GB", because some of people will want "en-US" etc.

I will try to add a dropdown with available spellchecker languages for platforms which does not support native spellchecker (macOS).

**Comment by JOduMonT** [comment]
> 2\. Unfortunately it seems that "en" is not available in spellchecker for your linux instance. In this case you have to select a english version which supports spellchecker. We cannot decide that if you select "en" then spellchecker will be set to "en-GB", because some of people will want "en-US" etc.

thank, in my case I choose en-ca, which probably represent 45% of my where I learned my english
