### ISSUE TITLE
CI/CD support or cli export

### ISSUE THREAD

**Issue by mibofra** [GetPublii/Publii#924]
Publii doesn't have any command to export a site manually from command line.

If I want to export it using any CI/CD service (not only Gitlab CI but also, with anything else isn't Pages), I've to first manually sync the site offline in an output dir, after upload the dir with all the sources, and then the script can copy it where needed.

This makes the size of a repo bigger, if I want to use it in a CI setup, where I could build the site directly where the runner is running, or simply I can't build a site without a display server, given any input source code of a Publii site.

Suggestion: making a dedicated application, lighter than the whole CMS+builder, headless, just to build the sites from cli or scripts?

**Comment by dziudek** [comment]
I am working on such tool in the meantime (unfortunately no ETA yet). I am closing this issue as it will be a separate project, so this issue is not strictly related to the Publii core functionality.

**Comment by fungs** [comment]
This feature is desperately needed to outsource the build step to external pipelines. These typically utilize (Docker) containers as build runtimes. Also, for Git-based approaches, when the sources are kept in a Git repo, it does not make too much sense to add/commit both the sources and artifacts (html pages) into the same repo logically-wise.

IMO the CLI build trigger should be part of the main release (it is just exposing the button press via command line, right?). This should be preferred in order to align the source management and build parts by official program version.
