### ISSUE TITLE
Netlify Server Deploy Error

### ISSUE THREAD

**Issue by ebru** [GetPublii/Publii#956]
When syncing the site with Netlify I'm getting the following error. The issue has started after 13th April on my side and I could not manage to sync the site since then.

```
An error occurred during connecting to the server. Please check your server settings or try again.
```

![image](https://user-images.githubusercontent.com/45464584/115124767-b85a4300-9fcc-11eb-9cf7-53ef3a755ac2.png)

The server settings are working fine. Test connection also returns success. 

![image](https://user-images.githubusercontent.com/45464584/115124754-9bbe0b00-9fcc-11eb-86b8-84e4c2c7c1c4.png)

Here are the logs as well:

deployment-process.log

```
[Sat, 17 Apr 2021 19:31:50 GMT] Netlify ERROR: false
```

deployment-errors.log is empty.

**Version:** 0.38.1

**Comment by dziudek** [comment]
Hi,

Could you check if on the Netlify side there are some useful logs? I have checked the deploy right now and for me it is working fine. I have used for test quite big website with over 200 files which contains images, html etc. So the flow seems to be working fine at a normal case.

**Comment by ebru** [comment]
Thanks for the return. I can confirm that it works for me at the moment after deleting the old repo on Netlify and creating a new one. But I am not sure what was the root cause to break the working connection earlier. 

If I face it again, I will be letting you know.

**Comment by tuopppi** [comment]
I'm facing the same issue. From Netlify console I'm seeing following message:
`6:58:39 PM: Creating deploy upload records` and the deployment is left to "Uploading" status
![image](https://user-images.githubusercontent.com/182331/162782684-cf067881-9c49-4375-a9ec-cb094ce568d1.png)

**Comment by htejera** [comment]
> 

I have the same error that @tuopppi describe

- Version: 0.39.1 (build 15486)
- Windows 10

I have a relatively large site (> 500 pages with images). 

When I synchronize the site, and after about 1 minute, the following error occurs:


![sync-netlify](https://user-images.githubusercontent.com/38955523/162809016-984284cf-e9ea-4af5-975b-fefacc5384c7.jpg)

It seems to be able to connect to Netlify, since it registers a deploy, but it remains in *Uploading* state.

Unfortunately on the Netlify side, the logs are not very useful to determine the cause of the problem.

![deploy-netlify](https://user-images.githubusercontent.com/38955523/162809134-0798a1ed-0dc7-4547-9d31-cf1a7a048e47.jpg)

**Comment by tuopppi** [comment]
@htejera The issue in my case was that the deployment/theme contained a completely empty file (main.css in my case). After I added some text content into it, everything started working again.
