### ISSUE TITLE
Feature suggestion: Memberships, User Authentication, Protected Posts

### ISSUE THREAD

**Issue by candideu** [GetPublii/Publii#967]
I discovered Publii today and really appreciate this free and open-source project!

To echo other feature requests linked to milestone [0.40.0](https://github.com/GetPublii/Publii/milestone/16) ([Payment System with PayPal](https://github.com/GetPublii/Publii/issues/557) and [Stripe Integration](https://github.com/GetPublii/Publii/issues/607), I would love to see an option to have read-only memberships (free and paid). People could register/sign, log-in, log-out, save posts, etc. There could also be an option where certain posts are reserved for members and require logging in.

I'm not very tech-savvy, but maybe an integration with auth0 or Keycloak could facilitate this...

**Comment by strelok899** [comment]
Would also like this feature

**Comment by candideu** [comment]
Authorizer seems to be a promising open-source authorization tool: https://authorizer.dev/

It's possible to integrate with static sites as well

**Comment by dziudek** [comment]
Such functionality is strictly connected with specific hosting services so it won't be integrated into Publii core. Maybe as a plugin in the future (if proper service coverage will be available). That's why I am closing this issue now - we have no plans for Publii core functionality like this at this moment.
